#
# Copyright (C) 2020 Signal Messenger, LLC.
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "signal-neon-futures"
version = "0.1.0"
authors = ["Jordan Rose <jrose@signal.org>"]
license = "AGPL-3.0-only"
edition = "2018"

[dependencies]
neon = "0.5.0"
futures = "0.3.7"
